// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingJournal.Data;

#nullable disable

namespace TradingJournal.Data.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20251003205522_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TradingJournal.Data.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("TradingJournal.Data.Models.ManagementAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AdjustmentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("ManagementAdjustments");
                });

            modelBuilder.Entity("TradingJournal.Data.Models.StrategyCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StrategyCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ColorHex = "#FF5733",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemDefined = true,
                            Name = "Breakout"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ColorHex = "#33FF57",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemDefined = true,
                            Name = "Pullback"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            ColorHex = "#3357FF",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemDefined = true,
                            Name = "Reversal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            ColorHex = "#FF33A1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemDefined = true,
                            Name = "Trend Continuation"
                        });
                });

            modelBuilder.Entity("TradingJournal.Data.Models.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DisciplineScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmotionAtEntry")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmotionAtExit")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmotionDuringTrade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExitDateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HoldingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonsLearned")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketStructure")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mistakes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlannedRRRatio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PositionSize")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProfitLossCurrency")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProfitLossR")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualityRating")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RealizedRRRatio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RiskPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetupType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLoss")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TakeProfit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryDateTime")
                        .HasDatabaseName("IX_Trade_EntryDateTime");

                    b.HasIndex("SetupType")
                        .HasDatabaseName("IX_Trade_SetupType");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("IX_Trade_Symbol");

                    b.HasIndex("Symbol", "EntryDateTime")
                        .HasDatabaseName("IX_Trade_Symbol_EntryDateTime");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("TradingJournal.Data.Models.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomFieldDefinitions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DatabaseEncrypted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultRiskPercentage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableBiometricAuth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserPreferences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CustomFieldDefinitions = "{}",
                            DatabaseEncrypted = false,
                            DefaultCurrency = "USD",
                            DefaultRiskPercentage = 1m,
                            EnableBiometricAuth = false,
                            Theme = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TradingJournal.Data.Models.Attachment", b =>
                {
                    b.HasOne("TradingJournal.Data.Models.Trade", "Trade")
                        .WithMany("Attachments")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("TradingJournal.Data.Models.ManagementAdjustment", b =>
                {
                    b.HasOne("TradingJournal.Data.Models.Trade", "Trade")
                        .WithMany("Adjustments")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("TradingJournal.Data.Models.Trade", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
