<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Calculations\" />
    <Folder Include="Validators\" />
    <PackageReference Include="FluentValidation" Version="11.5.0" />
    <!-- Reference data layer for models -->
    <ProjectReference Include="..\TradingJournal.Data\TradingJournal.Data.csproj" />
  </ItemGroup>
</Project>
